@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

BookKeeper *-right->  Order
Order *--> Deadline
Order *--> OrderDate
Order *--> Price
Order *--> Remark
Order *--> Status

@enduml
