@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "BookKeeper Storage" #F4F6F6{
Class "<<interface>>\nBookKeeperStorage" as BookKeeperStorage
Class JsonBookKeeperStorage
Class JsonSerializableBookKeeper
Class JsonAdaptedClient
Class JsonAdaptedTag
Class JsonAdaptedOrder
}

}

Class HiddenOutside #C4A484
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" BookKeeperStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> BookKeeperStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonBookKeeperStorage .up.|> BookKeeperStorage
JsonBookKeeperStorage ..> JsonSerializableBookKeeper
JsonSerializableBookKeeper --> "*" JsonAdaptedClient
JsonSerializableBookKeeper --> "*" JsonAdaptedOrder
JsonAdaptedClient --> "*" JsonAdaptedTag
JsonAdaptedTag -[hidden]right-> JsonAdaptedOrder
JsonAdaptedClient --> "*" JsonAdaptedOrder

@enduml
